export const LOAD_RACERS_SUCCESS = 'LOAD_RACERS_SUCCESS';
export const LOAD_RACES_SUCCESS = 'LOAD_RACES_SUCCESS';
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';

export const SET_DATA_LOADING_FLAG = 'SET_DATA_LOADING_FLAG';
export const DATA_LOADING_FAILURE = 'DATA_LOADING_FAILURE';


export const ADD_RACE = 'ADD_RACE';
export const SET_RACERS_POSITION = 'SET_RACERS_POSITION';
